name: Tests

on: 
  pull_request: 
    branches:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Start container
      run: docker-compose up
    - name: Run tests
      run: yarn test
